#lang sicp
(define (c+ x y)
  (let ((z (make-connector)))
    (adder x y z)
    z))
(define (c- z x)
  (let ((y (make-connector)))
    (adder x y z)
    y))
(define (c* x y)
  (let ((z (make-connector)))
    (multiplier x y z)
    z))
(define (c/ z x)
  (let ((y (make-connector)))
    (multiplier x y z)
    y))
(define (cv v)
  (let ((x (make-connector)))
    (constant v x)
    x))